version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./linleasing/dist:/usr/share/nginx/html/linleasing
      - ./web-page/dist:/usr/share/nginx/html/web-page
      - ./linleasing-reg/dist:/usr/share/nginx/html/linleasing-reg
      # - ./index/dist:/usr/share/nginx/html 
  nextauth:
    image: nextauth
    build: 
      context: ./nextjs-auth
      dockerfile: Dockerfile
    ports:
      - "3004:3004" 
  # linleasing:
  #   image: linleasing
  #   build:
  #     context: ./vitejs
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:80"
    
  # app6:
  #   image: app6
  #   build: 
  #     context: ../../TRD_APP6
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3006:3006" 
  # app4:
  #   image: app4
  #   build: 
  #     context: ../../TRDAPP4
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3004:3004" 
  # app7:
  #   image: app7
  #   build: 
  #     context: ../../TRD_DOC_7
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3007:3007" 