version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
      - ./asset:/usr/share/nginx/html/asset
  callline-webhook:
    image: callline-webhook  
    build: 
      context: ./callline-webhook
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
  websocket-active-batch:
    image: websocket-active-batch  
    build: 
      context: ./websocket-active-batch
      dockerfile: Dockerfile
      target: final
    ports:
      - "3000:3000"
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    # Add any environment variables your service needs
    environment:
      - NODE_ENV=production
    # Add dependencies if needed (like a database)
    # depends_on:
    #   - database